export type OrderState = "DRAFT" | "CHECKOUT_VALIDATING" | "PAYMENT_PENDING" | "PAID" | "ACCEPTED" | "PREPARING" | "READY_FOR_PICKUP" | "OUT_FOR_DELIVERY" | "COMPLETED" | "CANCELLATION_PENDING" | "CANCELLED" | "REFUND_PENDING" | "PARTIALLY_REFUNDED" | "REFUNDED";
export type OrderEvent = "VALIDATE" | "REQUEST_PAYMENT" | "PAY" | "ACCEPT" | "PREPARE" | "READY" | "DISPATCH" | "COMPLETE" | "REQUEST_CANCEL" | "CANCEL" | "REQUEST_REFUND" | "PARTIAL_REFUND" | "REFUND";

const transitions: Record<OrderState, Partial<Record<OrderEvent, OrderState>>> = {
  DRAFT: { VALIDATE: "CHECKOUT_VALIDATING", REQUEST_CANCEL: "CANCELLATION_PENDING" },
  CHECKOUT_VALIDATING: { REQUEST_PAYMENT: "PAYMENT_PENDING", REQUEST_CANCEL: "CANCELLATION_PENDING" },
  PAYMENT_PENDING: { PAY: "PAID", REQUEST_CANCEL: "CANCELLATION_PENDING" },
  PAID: { ACCEPT: "ACCEPTED", REQUEST_REFUND: "REFUND_PENDING", REQUEST_CANCEL: "CANCELLATION_PENDING" },
  ACCEPTED: { PREPARE: "PREPARING", REQUEST_CANCEL: "CANCELLATION_PENDING" },
  PREPARING: { READY: "READY_FOR_PICKUP", DISPATCH: "OUT_FOR_DELIVERY", REQUEST_CANCEL: "CANCELLATION_PENDING" },
  READY_FOR_PICKUP: { COMPLETE: "COMPLETED", REQUEST_REFUND: "REFUND_PENDING" },
  OUT_FOR_DELIVERY: { COMPLETE: "COMPLETED", REQUEST_REFUND: "REFUND_PENDING" },
  COMPLETED: { REQUEST_REFUND: "REFUND_PENDING" },
  CANCELLATION_PENDING: { CANCEL: "CANCELLED" },
  CANCELLED: {},
  REFUND_PENDING: { PARTIAL_REFUND: "PARTIALLY_REFUNDED", REFUND: "REFUNDED" },
  PARTIALLY_REFUNDED: { REQUEST_REFUND: "REFUND_PENDING" },
  REFUNDED: {},
};

export function transitionOrder(state: OrderState, event: OrderEvent): OrderState {
  const next = transitions[state][event];
  if (!next) throw new Error(`非法訂單狀態轉換：${state} -> ${event}`);
  return next;
}
