"use client";

import Link from "next/link";
import { Check, ChefHat, ClipboardList, Home, Share2, ShoppingBag, Truck } from "lucide-react";
import { PageHeader } from "@/presentation/components/page-header";
import { useOrder } from "@/presentation/providers/order-provider";

export default function OrderSuccessPage() {
  const { state } = useOrder();
  const order = state.lastOrder ?? { id: "demo", number: "A2026071900123", amount: 329, branchName: "台北信義店", mode: "delivery" as const, paymentMethod: "LINE Pay" as const, createdAt: Date.now() };
  const steps = [{ label: "已付款", icon: Check, state: "complete" }, { label: "店家已接單", icon: Check, state: "complete" }, { label: "製作中", icon: ChefHat, state: "active" }, { label: "待取餐／配送中", icon: Truck, state: "pending" }, { label: "已完成", icon: ShoppingBag, state: "pending" }];
  return <main className="page-gradient"><PageHeader title="訂單成立" subtitle="感謝您的訂購，店家已收到訂單。" /><section className="page-card"><div className="success-hero"><div className="success-icon"><Check size={42} /></div><h1>付款成功，餐點製作中</h1><p className="muted">訂單編號 {order.number}</p><strong className="price" style={{ fontSize: "1.5rem" }}>預計 20–30 分鐘完成</strong></div><div className="page-card__body"><div className="progress-steps">{steps.map(({ label, icon: Icon, state: stepState }) => <div className={`progress-step ${stepState === "complete" ? "is-complete" : stepState === "active" ? "is-active" : ""}`} key={label}><span><Icon size={20} /></span><strong>{label}</strong></div>)}</div></div></section><section className="page-card"><div className="page-card__header"><h2>訂單摘要</h2></div><div className="page-card__body summary-list"><div className="summary-row"><span>訂購店家</span><strong>{order.branchName}</strong></div><div className="summary-row"><span>訂單金額</span><strong className="price">NT$ {order.amount}</strong></div><div className="summary-row"><span>付款方式</span><span className="line-pay">LINE <b>Pay</b></span></div><div className="summary-row"><span>訂購方式</span><strong>{order.mode === "delivery" ? "外送" : "自取"}</strong></div></div></section>{state.room && <section className="page-card" style={{ background: "#fffaf0" }}><div className="page-card__body"><h3>一起點明細已保存</h3><p className="muted">每位參與者的餐點與金額明細已保存在本次訂單快照。</p></div></section>}<div style={{ width: "min(920px, calc(100% - 28px))", margin: "0 auto", display: "grid", gap: 10 }}><button type="button" className="button button--primary button--block"><ClipboardList size={18} />查看訂單</button><Link href="/menu" className="button button--outline button--block"><Home size={18} />回到首頁</Link><button type="button" className="button button--outline button--block"><Share2 size={18} />分享結果</button></div></main>;
}
